
export default [
    {
        id: "mask-bwa",
        title: { fr: "Masque Dogon", en: "Dogon Mask", wo: "Maask Dogon" },
        description: {
            fr: "Ce masque cérémoniel Dogon du Mali représente un esprit ancestral. Utilisé lors de rituels funéraires, il incarne la connexion entre le monde des vivants et celui des ancêtres. Les Dogons sont réputés pour leur cosmogonie complexe et leurs traditions artistiques millénaires.",
            en: "This ceremonial Dogon mask from Mali represents an ancestral spirit. Used in funeral rituals, it embodies the connection between the world of the living and that of the ancestors. The Dogon are renowned for their complex cosmogony and thousand-year-old artistic traditions.",
            wo: "Maask Dogon bii jëkk na ci Mali, dafa melni ruu jabar. Dañu ko jëfandikoo ci sérémoniy ñu def bu ku dee, te dafa wone lëkkalekaay ci àdduna bu ñu moom ak sa yaay ak sa baay yu dee. Dogon yi dañu bari ci xam-xam bu rafet ak cosaan yu guddi.",
        },
        artist: "Artisan Dogon",
        period: "19ème siècle",
        origin: "Mali",
        category: "Sculpture",
        model3dUrl: "/dogon2.glb",
        imageUrl: "/assets/dogon.jpg",
        qrCode: "MCN-001",
    },
    {
        id: "statue-dogon",
        title: { fr: "Statue Nok", en: "Nok Statue", wo: "Statiy Nok" },
        description: {
            fr: "Cette terre cuite de la culture Nok (500 av. J.-C. - 200 ap. J.-C.) du Nigeria est l'une des plus anciennes sculptures d'Afrique subsaharienne. Les Nok maîtrisaient la métallurgie du fer et créaient des œuvres d'une sophistication remarquable.",
            en: "This terracotta from the Nok culture (500 BC - 200 AD) of Nigeria is one of the oldest sculptures in sub-Saharan Africa. The Nok mastered iron metallurgy and created works of remarkable sophistication.",
            wo: "Teer kuit bii jëkk na ci cosaan Nok (500 av. J.-C. - 200 ap. J.-C.) ci Nigeria, te dafa am ci yëf yu mag yu Afrik subsaharienne. Nok yi dañu xam liggéey bu rafet ci fer.",
        },
        artist: "Culture Nok",
        period: "500 av. J.-C.",
        origin: "Nigeria",
        category: "Terre cuite",
        model3dUrl: "/nok2.glb",
        imageUrl: "/assets/nok.jpg",
        qrCode: "MCN-002",
    },
    {
        id: "throne-ashanti",
        title: { fr: "Trône Ashanti", en: "Ashanti Throne", wo: "Troon Ashanti" },
        description: {
            fr: "Ce trône royal Ashanti du Ghana symbolise le pouvoir et la continuité dynastique. Recouvert de feuilles d'or, il représente l'âme de la nation Ashanti. Chaque élément décoratif raconte une histoire de bravoure et de sagesse.",
            en: "This royal Ashanti throne from Ghana symbolizes power and dynastic continuity. Covered in gold leaf, it represents the soul of the Ashanti nation. Each decorative element tells a story of bravery and wisdom.",
            wo: "Troon bii jëkk na ci Ghana, dafa melni doole ak cosaan bu guddi. Dañu ko tefes ci wàr, te dafa wone ruu réew Ashanti. Bëpp xeetu rafet dafa xalaat ab tarix bu gëna.",
        },
        artist: "Artisans Ashanti",
        period: "18ème siècle",
        origin: "Ghana",
        category: "Mobilier royal",
        model3dUrl: "/trone2.glb",
        imageUrl: "/assets/trone.jpg",
        qrCode: "MCN-003",
    },
    {
        id: "mask-fang",
        title: { fr: "Masque Fang", en: "Fang Mask", wo: "Maask Fang" },
        description: {
            fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
            en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
            wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
        },
        artist: "Artisan Fang",
        period: "20ème siècle",
        origin: "Gabon",
        category: "Sculpture",
        model3dUrl: "/fang2.glb",
        imageUrl: "/assets/fang.jpg",
        qrCode: "MCN-005",
    },
    {
        id: "femme-fs",
        title: { fr: "Femme fs", en: "Fang Mask", wo: "Maask Fang" },
        description: {
            fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
            en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
            wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
        },
        artist: "Artisan Fang",
        period: "20ème siècle",
        origin: "Gabon",
        category: "Sculpture",
        model3dUrl: "/femme_fs1.glb",
        imageUrl: "/assets/femme_fs.jpg",
        qrCode: "MCN-005",
    },
    {
        id: "femme-ch",
        title: { fr: "Femme h", en: "Fang Mask", wo: "Maask Fang" },
        description: {
            fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
            en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
            wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
        },
        artist: "Artisan Fang",
        period: "20ème siècle",
        origin: "Gabon",
        category: "Sculpture",
        model3dUrl: "/femme_ch1.glb",
        imageUrl: "/assets/femme_ch.jpg",
        qrCode: "MCN-005",
    },
    {
        id: "buf-ch",
        title: { fr: "Femme h", en: "Fang Mask", wo: "Maask Fang" },
        description: {
            fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
            en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
            wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
        },
        artist: "Artisan Fang",
        period: "20ème siècle",
        origin: "Gabon",
        category: "Sculpture",
        model3dUrl: "/buf1.glb",
        imageUrl: "/assets/buf.jpg",
        qrCode: "MCN-005",
    },
];